name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔨 Build for production
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NODE_ENV: production
        run: npm run build:prod

      - name: 📋 List build output
        run: ls -la dist/

      - name: 📤 FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./dist/
          dangerous-clean-slate: false
          log-level: verbose
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.example
            *.md
            tests/**
            Archive/**
            Legacy_Docs/**
            scripts/**
            supabase/**
            *.sql
            *.cjs
            *.config.js
            package*.json

      - name: ✅ Deployment Complete
        run: echo "🎉 Successfully deployed to Hostinger!"